extends: airbnb-base
plugins:
  - import
rules:
  no-shadow: off
  no-underscore-dangle: off
  consistent-return: off
  no-prototype-builtins: off
  no-use-before-define: off
  arrow-parens:
    - error
    - "as-needed"
env:
  es6: true
  node: true
  mocha: true