sudo: required
language: node_js
node:
addons:
  postgresql: "9.5"
services:
  - postgresql
before_script:
  - psql -c 'create database tallerify_travis;' -U postgres
script:
  - '[ "$TRAVIS_PULL_REQUEST" != "false" ] && npm run lint'
  - npm test
  - '[ "$TRAVIS_PULL_REQUEST" != "false" ] && npm run coverage && npm run codecov'
env:
  - TEST_DATABASE_URL=postgres://postgres@localhost:5432/tallerify_travis
notifications:
  email: false
  slack: tallerify:3BddOwjmsqmpRjYFXvbRZu1r
