sudo: required
language: node_js
node:
addons:
  postgresql: "9.5"
services:
  - postgresql
before_script:
  - psql -c 'create database tallerify_travis;' -U postgres
env:
  - TEST_DATABASE_URL=postgres://postgres@localhost:5432/tallerify_travis
after_success:
  - npm run coverage
  - npm run codecov
  - npm run lint
notifications:
  email: false
  slack: tallerify:3BddOwjmsqmpRjYFXvbRZu1r
