version: "3"
services:
  db:
    image: postgres:9.5
    ports:
      - "5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=tallerify_dev
  web:
    ports:
      - "3000:3000"
    env_file:
      - .env
    build: .
    depends_on:
      - db

volumes:
  db-data:
