module.exports = {
  artists: 'artists',
  albums: 'albums',
  albums_artists: 'albums_artists',
  tracks: 'tracks',
  tracks_rating: 'tracks_rating',
  artists_tracks: 'artists_tracks',
  users: 'users',
  admins: 'admins',
  users_tracks: 'users_tracks',
  playlists: 'playlists',
  users_users: 'users_users',
  users_artists: 'users_artists',
  playlists_tracks: 'playlists_tracks',
  playlists_albums: 'playlists_albums',
};
